server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: provider-first
  datasource:
    master:
      jdbc-url: jdbc:mysql://www.susheyougou.club:3308/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://www.susheyougou.club:3309/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: reader   # 只读账户
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://www.susheyougou.club:3310/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: reader   # 只读账户
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver